FROM golang:alpine AS start-point

# file system watcher and bash
RUN apk update && apk add bash inotify-tools

# Set necessary environmet variables needed for our image
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

# Move to working directory /build
WORKDIR /build

# Copy the code into the container
COPY . /build

# Downloads modules
RUN go mod download

# Installs dlv debugger for remote debugging
RUN go get github.com/go-delve/delve/cmd/dlv

# Builds executable that can be started with a debug session
RUN go build -gcflags "all=-N -l" -o /server /build/main.go